{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-3.0.3-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.jar",
          "size": 439533,
          "sha512": "531874cab30ef823b5b885937dec2729a6f6e92dd9f3f9e79c63d1c3642f41fee638dea32f99237482f4ee1241bb85d9038bfc68e1423ca8c5abe2dda2b6fe84",
          "sha256": "996a9bd5ac75f94320770634c4f473cec3948a76f2a5d478d63561c6b4994a66",
          "sha1": "f4ea6823e718f747cc89a1a75f487f13d06d139e",
          "md5": "762f47e1e01622d767144e725665edfd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.jar",
          "size": 439533,
          "sha512": "531874cab30ef823b5b885937dec2729a6f6e92dd9f3f9e79c63d1c3642f41fee638dea32f99237482f4ee1241bb85d9038bfc68e1423ca8c5abe2dda2b6fe84",
          "sha256": "996a9bd5ac75f94320770634c4f473cec3948a76f2a5d478d63561c6b4994a66",
          "sha1": "f4ea6823e718f747cc89a1a75f487f13d06d139e",
          "md5": "762f47e1e01622d767144e725665edfd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT-sources.jar",
          "size": 196740,
          "sha512": "7142ecd893090f76f2e5a26d9b728c227e84644ca01943a456fdfff35b5e5cf307167ce114ba7448f90171ad3a4d1150aea0382e57467da3727f0f010b9eca11",
          "sha256": "cb69b1223da83915f9fca19a9f0f39989cfd9484c1763a01ed31dc4fb150f214",
          "sha1": "ff83a6c2b92a711453530d36df766ed3cb6ce850",
          "md5": "03545119c346f02d0e8dc39d0f5a9da3"
        }
      ]
    }
  ]
}
