{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-3.0.4-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.klib",
          "size": 491843,
          "sha512": "0e83c7658dca5b11ad9f1fb14079f04f0ec987e648bf821a875ac7fe4d5248e0ec05b15c4da7dd751a6e88621119868356faf0f06a029425a06eaaf50f896bc0",
          "sha256": "5178744953c00f194143789901ea75bc5e43e5e229589531517706ee71a06c0b",
          "sha1": "4fa1b962b20d1c9e004b2a67db551d8d362b9492",
          "md5": "9d04383abf4d3a5c13a33f1be4eebbb8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.klib",
          "size": 491843,
          "sha512": "0e83c7658dca5b11ad9f1fb14079f04f0ec987e648bf821a875ac7fe4d5248e0ec05b15c4da7dd751a6e88621119868356faf0f06a029425a06eaaf50f896bc0",
          "sha256": "5178744953c00f194143789901ea75bc5e43e5e229589531517706ee71a06c0b",
          "sha1": "4fa1b962b20d1c9e004b2a67db551d8d362b9492",
          "md5": "9d04383abf4d3a5c13a33f1be4eebbb8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT-sources.jar",
          "size": 191237,
          "sha512": "2f338872cb7aa86c14e00e80513109bc92b18796b9fe9a92e0d05fc760a447d39e3efc34ff7504764bc85885603fc7365286115589e03a3db4e45ecf5504af71",
          "sha256": "2afa69ba57c1ca743d93f616bebe1e310caf78de7cb23af02e45a99ee0da92ad",
          "sha1": "12be3571d8ee469f6c64ec4f855c19c5196ef587",
          "md5": "1fdca7d5ced9c2707936e85f7e73cca4"
        }
      ]
    }
  ]
}
