{
  "formatVersion": "1.1",
  "component": {
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-3.0.4-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-3.0.4-SNAPSHOT.jar",
          "size": 113922,
          "sha512": "5d64538e68c5b8cd69ed750ecfb6bcf4b577425e9ec900c880a2e2529df3af9f1bf742b3427c106fcf52e95c966a6c7f7b667db51fa1cf2c7f0a7e2d2d108298",
          "sha256": "396b760d960bcdfff3f7914a0da65c80078ccbddfce635b82c11baaa3955184d",
          "sha1": "ad1e1e33c7584be2c1b16b1e9d78c25a21b5770c",
          "md5": "c9ab799064c81021ada3695cf09092a2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-3.0.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-3.0.4-SNAPSHOT-sources.jar",
          "size": 194486,
          "sha512": "9966d70ee34bd78e891c1ddfa262ccf0752e47d3db87baa821eec0a8ba2c8505c6392ec10bb130324f804c594ebfa64106bcb4b5ada105d548168ec26c98a7a8",
          "sha256": "baaacb227df4ae8d2f1843976aa3bda07149470c14aa1831f10154dfd3f28ee4",
          "sha1": "02c176c6858c9246e630a0e28428a00ca4090a3d",
          "md5": "f6425d454f80bef4799c04f1e4b55125"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.4-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.4-SNAPSHOT"
      }
    }
  ]
}
