{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-3.0.4-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.jar",
          "size": 436475,
          "sha512": "15197e9f8359cfa0961aee1903b91ebd27637cb8618003126bea48b21508a258bb39a4a784710fabcdef9825043844ace6d519ee66666d1fe128811e7dc93960",
          "sha256": "d6478fc3bb42917509306458b447e2b51209325f86b9a730fd0ef3c25200a7e6",
          "sha1": "396e1633c199ca4c817e2a873085740ba3f0a772",
          "md5": "d92e02fd3c512c3978645da68d97cbd3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT.jar",
          "size": 436475,
          "sha512": "15197e9f8359cfa0961aee1903b91ebd27637cb8618003126bea48b21508a258bb39a4a784710fabcdef9825043844ace6d519ee66666d1fe128811e7dc93960",
          "sha256": "d6478fc3bb42917509306458b447e2b51209325f86b9a730fd0ef3c25200a7e6",
          "sha1": "396e1633c199ca4c817e2a873085740ba3f0a772",
          "md5": "d92e02fd3c512c3978645da68d97cbd3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.4-SNAPSHOT-sources.jar",
          "size": 196772,
          "sha512": "dd1a589e3bfb57b2e304d0ad6f65ef258c9c1a2be228cce7e23acaf3b05fc0c92490af37b49927869bbcf79e3bd892f4bbffb92f931c7c461d5b9f6e1a79ffcc",
          "sha256": "994f3993d6ec9767ae8546782d4d9d95a30d3205d85280d5e86cc79d925422ae",
          "sha1": "b31fb44bd85496a848de76c0a00e17315c58bcab",
          "md5": "052c2c12645eb4ee6a995128bef53293"
        }
      ]
    }
  ]
}
