{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.4-SNAPSHOT/snakeyaml-engine-kmp-3.0.4-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT.klib",
          "size": 495645,
          "sha512": "756f10255e74debf4a8cf70857c1afea4d4746f6350920cf09def14b9047fc5abb4cf22a30baed94b6a1811a081012bde9a55d6dc87d58a38970a963fe24db00",
          "sha256": "01a0a8d9346af805c237f3350a04625f41fbf925c6c9cad88f77c88cf57ad2ab",
          "sha1": "ea91d344b63df17f788750a807175ced8d18f178",
          "md5": "148f2a56b50388bd7598f8a446bab377"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT-sources.jar",
          "size": 189733,
          "sha512": "c69196be41ac9f939882f58f84b854b4a695a60f4beeb1a366dc580a53692764bd325965eec6baec5d916665f8540d4afe96931ef80c57c288359535c2c66be9",
          "sha256": "c81d855c40758cb5c7e975b1ef9f110cf0fd4be5194b32acd98e3b19deb3df8a",
          "sha1": "689f5c5367d8f5a98ab9ba1e121f29bcdeebc343",
          "md5": "f325ef3518ad61e6ab39aa1aa84f78e3"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT-metadata.jar",
          "url": "snakeyaml-engine-kmp-tvosx64-3.0.4-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
