{
  "formatVersion": "1.1",
  "component": {
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-3.0.3-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-3.0.3-SNAPSHOT.jar",
          "size": 113921,
          "sha512": "3d7c0eba38182534b488079213ff48399971bf20213f76580c10155badc1849f9e25200add01d899b52f1dd9ba23a14d74dcafaf5805050927377e5c702c18e2",
          "sha256": "b5588cca45ead303a61bc235ee8539abfa1eb0bd6434cb5c2e19c0ca677be793",
          "sha1": "91d1c691b41b6bfc3cced72159c7f0e06d02b595",
          "md5": "51c5dba650c195f020fcb2536e0c3583"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-3.0.3-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-3.0.3-SNAPSHOT-sources.jar",
          "size": 194454,
          "sha512": "dfcbb7414d36436862b3326d4b3623943bb7369db1e33e586751b30b12b0beab1ea2861029771298909c31d4470d790e633f358990d622a880c5eb8f3b3914be",
          "sha256": "3eaf4216f5f106afcc1e4362948d299488c60cb95de0cbe3b6a7fb7348cdc3dd",
          "sha1": "4d5f6b4b583619bb8aa9ad979671e7b11e96d173",
          "md5": "a76b3710ae7e6f9b4f3696ef92708849"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-iosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-jvm-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-macosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-wasm-js/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-wasm-js-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-wasm-js",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-3.0.3-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "3.0.3-SNAPSHOT"
      }
    }
  ]
}
