{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.3-SNAPSHOT/snakeyaml-engine-kmp-3.0.3-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-3.0.3-SNAPSHOT.klib",
          "size": 495243,
          "sha512": "c1de3222f0f36a1319618232df1aedee8486ef02b5474dd4184bdfcd354c6f4feefb4a98faa472efdc695682eaa582db6b5845e476d55d7ca3a4f2fa7b2b784e",
          "sha256": "8df8da8fb084ea48a980a5cc76ee0df5c38ba642c9e6b928b2cfc6ddbdb53344",
          "sha1": "7abed3fb60dc171ab18dce67aa71f7ed9cad3a47",
          "md5": "72c64613628a2fa52ab480fca7af02e9"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-3.0.3-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-3.0.3-SNAPSHOT-sources.jar",
          "size": 189699,
          "sha512": "af61bc1e4087bcf68e819d45585aa421b9678e79d2996f349e941f628b0639240318834521c9a2eb1524f90bda08c29377016b63d844b793c314f43b6e755ea6",
          "sha256": "02e047767d0fe09c429c504f99dc605dbce1d50c099d67643a9f0103d1914f8d",
          "sha1": "06feffd42b7c0e8ee8231b7137dda8945c76a964",
          "md5": "56ae1a6c152a9489db5d09f7531e6200"
        }
      ]
    }
  ]
}
